#!/bin/bash
# Save the HTML report to a specific file

BOOK_PATH="$1"
OUTPUT_PATH="${2:-report.html}"

if [ -z "$BOOK_PATH" ]; then
    echo "Usage: $0 <path-to-book.pdf> [output.html]"
    echo "Example: $0 ~/Downloads/MyBook.pdf my_report.html"
    exit 1
fi

echo "Processing book and generating HTML report..."

# Run workflow and get response
RESPONSE=$(./scripts/upload_text.sh "$BOOK_PATH")

# Extract report fields
HTML_REPORT=$(echo "$RESPONSE" | jq -r '.report_html')
BOOK_TITLE=$(echo "$RESPONSE" | jq -r '.book_title')
TOP_GENRE=$(echo "$RESPONSE" | jq -r '.top_genre')

if [ -z "$HTML_REPORT" ] || [ "$HTML_REPORT" = "null" ]; then
    echo "Error: No HTML report in response"
    exit 1
fi

# Create styled HTML file
cat > "$OUTPUT_PATH" << EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Genre Analysis: $BOOK_TITLE</title>
    <style>
        body {
            font-family: 'Courier New', monospace;
            background: linear-gradient(135deg, #1e1e1e 0%, #2d2d30 100%);
            color: #d4d4d4;
            padding: 40px;
            margin: 0;
            min-height: 100vh;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background-color: #252526;
            border-radius: 12px;
            box-shadow: 0 8px 32px rgba(0,0,0,0.3);
            padding: 40px;
        }
        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 2px solid #4ec9b0;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #4ec9b0;
            margin: 0 0 10px 0;
        }
        .header .meta {
            color: #858585;
            font-size: 0.9em;
        }
        pre {
            background-color: #1e1e1e;
            padding: 30px;
            border-radius: 8px;
            border: 1px solid #3e3e42;
            overflow-x: auto;
            white-space: pre-wrap;
            line-height: 1.8;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #3e3e42;
            text-align: center;
            color: #858585;
            font-size: 0.9em;
        }
        .badge {
            display: inline-block;
            background-color: #4ec9b0;
            color: #1e1e1e;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: bold;
            margin: 0 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📚 Book Genre Analysis Report</h1>
            <div class="meta">
                <strong>$BOOK_TITLE</strong>
                <br>
                <span class="badge">$TOP_GENRE</span>
            </div>
        </div>
        <pre>$HTML_REPORT</pre>
        <div class="footer">
            Generated by Local Book Processor
            <br>
            Powered by Ollama • snowflake-arctic-embed (1024-dim) • 485 subgenres
            <br>
            <small>No API costs • 100% private • 100% local</small>
        </div>
    </div>
</body>
</html>
EOF

echo "✓ HTML report saved: $OUTPUT_PATH"
echo ""
echo "Opening in browser..."

# Open in default browser
if command -v open &> /dev/null; then
    open "$OUTPUT_PATH"
elif command -v xdg-open &> /dev/null; then
    xdg-open "$OUTPUT_PATH"
else
    echo "Manually open: $OUTPUT_PATH"
fi


