#!/bin/bash
# View the HTML report in your browser

BOOK_PATH="$1"

if [ -z "$BOOK_PATH" ]; then
    echo "Usage: $0 <path-to-book.pdf>"
    echo "Example: $0 ~/Downloads/MyBook.pdf"
    exit 1
fi

echo "Processing book and generating HTML report..."

# Run workflow and get response
RESPONSE=$(./scripts/upload_text.sh "$BOOK_PATH")

# Extract HTML report
HTML_REPORT=$(echo "$RESPONSE" | jq -r '.report_html')

if [ -z "$HTML_REPORT" ] || [ "$HTML_REPORT" = "null" ]; then
    echo "Error: No HTML report in response"
    echo "Response was:"
    echo "$RESPONSE"
    exit 1
fi

# Create HTML file
OUTPUT_FILE="/tmp/book_report_$(date +%s).html"

cat > "$OUTPUT_FILE" << EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Book Genre Analysis Report</title>
    <style>
        body {
            font-family: 'Courier New', monospace;
            background-color: #1e1e1e;
            color: #d4d4d4;
            padding: 40px;
            max-width: 1200px;
            margin: 0 auto;
            line-height: 1.6;
        }
        pre {
            background-color: #252526;
            padding: 20px;
            border-radius: 8px;
            border: 1px solid #3e3e42;
            overflow-x: auto;
            white-space: pre-wrap;
        }
        .header {
            text-align: center;
            color: #4ec9b0;
            margin-bottom: 30px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #858585;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📚 Book Genre Analysis Report</h1>
    </div>
    <pre>$HTML_REPORT</pre>
    <div class="footer">
        Generated by Local Book Processor • Powered by Ollama (snowflake-arctic-embed)
    </div>
</body>
</html>
EOF

echo "✓ HTML report created: $OUTPUT_FILE"
echo ""
echo "Opening in browser..."

# Open in default browser
if command -v open &> /dev/null; then
    open "$OUTPUT_FILE"
elif command -v xdg-open &> /dev/null; then
    xdg-open "$OUTPUT_FILE"
else
    echo "Could not open browser automatically."
    echo "Manually open: $OUTPUT_FILE"
fi

echo ""
echo "Report saved to: $OUTPUT_FILE"


